### ISSUE TITLE
Responsive

### ISSUE THREAD

**Issue by Valerie-Wissenburg** [chonnens/web-iv-portfolio-site#1]
Everything looks pretty good but one thing I've noticed that makes me wonder is, your responsive randomizer. Is there supposed to be a picture with it? I'm confused because we are at a base level so I'm just commenting to make sure that there is a plan.

**Comment by Valerie-Wissenburg** [comment]
Also – I wonder if your "skills used" on the projects page is too tiny when it shrinks down. 
Once, you get these fixed, you will be for sure at ADVANCED.

**Comment by elladurham** [comment]
I'd agree here with @Valerie-Wissenburg on the skills icons. Also, I realize your slider is still in dev, but is not currently responsive. Otherwise, good job considering each screen size.
