### ISSUE TITLE
HTML File

### ISSUE THREAD

**Issue by am548726** [chonnens/web-iv-portfolio-site#6]
- Apply formatting to your index file for easier reading
- Make sure to use proper heading levels because you are not using h1 but use h2 which is semantically wrong
- There are ending elements that don't have a opening tag such as in line 88, 100, and 153
- Lastly, I would validate the html file and that would solve the previous issue of missing tags and other specific problems and issues

<img width="1440" alt="screen shot 2015-11-13 at 2 26 21 pm" src="https://cloud.githubusercontent.com/assets/12190915/11156615/8da3e77c-8a12-11e5-94b5-047f8c018480.png">

<img width="1440" alt="screen shot 2015-11-13 at 2 31 04 pm" src="https://cloud.githubusercontent.com/assets/12190915/11156760/67586bfa-8a13-11e5-8deb-35454f1f26d6.png">

**Comment by am548726** [comment]
Cleanliness of Code Grade
Satisfactory

**Comment by elladurham** [comment]
Also, use smart typography instead of quote marks in your paragraphs like on line 66/67 of index.html.

**Comment by elladurham** [comment]
With lack of formatting and the other tidying up you can do before you submit your final prototype, this would currently fall under below satisfactory.

**Comment by chonnens** [comment]
@elladurham I'd love to use "smart typography" but unfortunately I'm not sure what the correct way is.
