### ISSUE TITLE
CSS File

### ISSUE THREAD

**Issue by am548726** [chonnens/web-iv-portfolio-site#8]
- Apply formatting to your css as it looks like it has been copied and pasted to your file
- There is a image file that is not properly link on line 101 on your custom.css

<img width="1440" alt="screen shot 2015-11-13 at 2 36 38 pm" src="https://cloud.githubusercontent.com/assets/12190915/11156975/82bc4c30-8a14-11e5-972e-ef1116267435.png">

**Comment by elladurham** [comment]
Yep, make sure to run your CSS through a formatter and clean up these other things. Eventually, remove unused queries.

**Comment by elladurham** [comment]
Begin a table of contents for your stylesheet.
